version: '3'
services:
  discovery:
    image: store/discovery:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always

  auth-service:
    image: store/auth-service:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/auth_user_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - discovery

  order-service:
    image: store/order-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/order_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
      - KAFKA_BOOTSTRAP_SERVERS:kafka:9092
    restart: always
    depends_on:
      - discovery

  gateway:
    image: store/gateway:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
    restart: always
    depends_on:
      - discovery
      - auth-service
      - order-service